apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/iconUrl: https://raw.githubusercontent.com/docker-library/docs/81187b7b50f5af5bdb64d75882f4d9c782ad52c3/rabbitmq/logo.png
  labels:
    app: rabbitmq
    provider: rabbit
    version: 3.6.11-management
    group: com.rabbit
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      provider: rabbit
      group: com.rabbit
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: https://raw.githubusercontent.com/docker-library/docs/81187b7b50f5af5bdb64d75882f4d9c782ad52c3/rabbitmq/logo.png
      labels:
        app: rabbitmq
        provider: rabbit
        version: 3.6.11-management
        group: com.rabbit
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        image: rabbitmq:3.6.11-management
        imagePullPolicy: IfNotPresent
        name: rabbitmq
        ports:
        - containerPort: 15672
          name: manager
        - containerPort: 5672
          name: broker
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      api.service.kubernetes.io/path: /
      fabric8.io/iconUrl: https://raw.githubusercontent.com/docker-library/docs/81187b7b50f5af5bdb64d75882f4d9c782ad52c3/rabbitmq/logo.png
    labels:
      expose: "true"
      app: rabbitmq
      provider: rabbit
      version: 3.6.11-management
      group: com.rabbit
    name: mqadmin
  spec:
    type: NodePort
    ports:
    - name: http
      port: 15672
      protocol: TCP
      targetPort: 15672
      nodePort: 31672
    selector:
      app: rabbitmq
      provider: rabbit
      group: com.rabbit
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      api.service.kubernetes.io/path: /
      fabric8.io/iconUrl: https://raw.githubusercontent.com/docker-library/docs/81187b7b50f5af5bdb64d75882f4d9c782ad52c3/rabbitmq/logo.png
    labels:
      expose: "true"
      app: rabbitmq
      provider: rabbit
      version: 3.6.11-management
      group: com.rabbit
    name: rabbitmq
  spec:
    ports:
    - name: http
      port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      app: rabbitmq
      provider: rabbit
      group: com.rabbit
