apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
   replicas: 1
   selector:
     matchLabels:
       app: redis
   template:
     metadata:
       labels:
         app: redis
     spec:
       containers:
       - name: redis
         image: redis
         command: ["/bin/sh","-c","exec redis-server /etc/redis/redis.conf"]
         resources:
           requests:
             cpu: 100m              #限制cpu的数量为0.1个
             memory: 100Mi      #限制内存为100M
         ports:
         - containerPort: 6379
         volumeMounts:
         - mountPath: /etc/redis
           name: redis-config
       volumes:
       - name: redis-config
         configMap:
           name: redis-conf
